/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg3.geometries_cs141a;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;

public class Geometries extends javax.swing.JFrame {

    /**
     * Creates new form Geometries
     */
    public Geometries() {
        initComponents();
        initializations();
        setTitleBar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_GeometryProblem = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelQuadratic = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        aJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cJTextField = new javax.swing.JTextField();
        quadraticJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        quadratic1JTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        quadratic2JTextArea = new javax.swing.JTextArea();
        jPanelCrammerRule = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        crammerC1JTextField = new javax.swing.JTextField();
        crammerB1JTextField = new javax.swing.JTextField();
        crammerC2JTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        crammerB2JTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        crammerA1JTextField = new javax.swing.JTextField();
        crammerA2JTextField = new javax.swing.JTextField();
        cramersJButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        crammer1JTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        crammer2JTextArea = new javax.swing.JTextArea();
        jPanelIntersectingLines = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        intersectingX1JTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        intersectingY1JTextField_I = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        intersectingX2JTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        intersectingY2JTextField_ = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        intersectingX3JTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        intersectingY3JTextField = new javax.swing.JTextField();
        intersectingY4JTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        intersectingX4JTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        IntersectingJButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        intersecting1JTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        intersecting2JTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemClear = new javax.swing.JMenuItem();
        jMenuItem_Print = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuGeometries = new javax.swing.JMenu();
        jMenuItem_Quadratic = new javax.swing.JMenuItem();
        jMenuItemCrammerRule = new javax.swing.JMenuItem();
        jMenuItemIntersectingLines = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        jPanelMain.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Geometries Problems");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select Geometry Problem");

        jComboBox_GeometryProblem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_GeometryProblem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lines" }));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(82, 82, 82))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_GeometryProblem, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_GeometryProblem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Main", jPanelMain);

        jPanelQuadratic.setBackground(new java.awt.Color(255, 204, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("a:");

        aJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aJTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("b:");

        bJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("c:");

        cJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cJTextFieldActionPerformed(evt);
            }
        });

        quadraticJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quadraticJButton.setText("Calculate");
        quadraticJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quadraticJButtonActionPerformed(evt);
            }
        });

        quadratic1JTextArea.setEditable(false);
        quadratic1JTextArea.setColumns(20);
        quadratic1JTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        quadratic1JTextArea.setLineWrap(true);
        quadratic1JTextArea.setRows(5);
        quadratic1JTextArea.setText("Enter the three coefficients a, b and c for the quadratic equation ax^2 + bx + c = 0 in order to determinethe real roots of the equation. Make sure a is not 0, else it will be a linear equation.");
        quadratic1JTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(quadratic1JTextArea);

        quadratic2JTextArea.setEditable(false);
        quadratic2JTextArea.setColumns(20);
        quadratic2JTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        quadratic2JTextArea.setRows(5);
        jScrollPane2.setViewportView(quadratic2JTextArea);

        javax.swing.GroupLayout jPanelQuadraticLayout = new javax.swing.GroupLayout(jPanelQuadratic);
        jPanelQuadratic.setLayout(jPanelQuadraticLayout);
        jPanelQuadraticLayout.setHorizontalGroup(
            jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuadraticLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuadraticLayout.createSequentialGroup()
                        .addGroup(jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQuadraticLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addGroup(jPanelQuadraticLayout.createSequentialGroup()
                                .addGroup(jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bJTextField)
                                    .addComponent(aJTextField))))
                        .addGap(18, 18, 18)
                        .addComponent(quadraticJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanelQuadraticLayout.setVerticalGroup(
            jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuadraticLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelQuadraticLayout.createSequentialGroup()
                        .addGroup(jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelQuadraticLayout.createSequentialGroup()
                                .addGroup(jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(aJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(bJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelQuadraticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addComponent(quadraticJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Quadratic", jPanelQuadratic);

        jPanelCrammerRule.setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coefficients of Lines", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("b1:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("c1:");

        crammerC1JTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        crammerC1JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crammerC1JTextFieldActionPerformed(evt);
            }
        });

        crammerB1JTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        crammerB1JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crammerB1JTextFieldActionPerformed(evt);
            }
        });

        crammerC2JTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        crammerC2JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crammerC2JTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("c2:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("b2:");

        crammerB2JTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        crammerB2JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crammerB2JTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("a1:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("a2:");

        crammerA1JTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        crammerA1JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crammerA1JTextFieldActionPerformed(evt);
            }
        });

        crammerA2JTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        crammerA2JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crammerA2JTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crammerC1JTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crammerB1JTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crammerA1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crammerC2JTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crammerB2JTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crammerA2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(crammerA2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(crammerB2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(crammerC2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(crammerA1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(crammerB1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(crammerC1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cramersJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cramersJButton.setText("Calculate");
        cramersJButton.setToolTipText("Find point of intersection using Crammer's Rule");
        cramersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cramersJButtonActionPerformed(evt);
            }
        });

        crammer1JTextArea.setEditable(false);
        crammer1JTextArea.setColumns(20);
        crammer1JTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        crammer1JTextArea.setLineWrap(true);
        crammer1JTextArea.setRows(5);
        crammer1JTextArea.setText("Enter the coefficients a1, a2, b1, b2, c1 and c2 for the two lines a1x + b1y = c1 and a2x + b2y = c2.");
        crammer1JTextArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(crammer1JTextArea);

        crammer2JTextArea.setEditable(false);
        crammer2JTextArea.setColumns(20);
        crammer2JTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        crammer2JTextArea.setLineWrap(true);
        crammer2JTextArea.setRows(5);
        crammer2JTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(crammer2JTextArea);

        javax.swing.GroupLayout jPanelCrammerRuleLayout = new javax.swing.GroupLayout(jPanelCrammerRule);
        jPanelCrammerRule.setLayout(jPanelCrammerRuleLayout);
        jPanelCrammerRuleLayout.setHorizontalGroup(
            jPanelCrammerRuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrammerRuleLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelCrammerRuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(jPanelCrammerRuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cramersJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanelCrammerRuleLayout.setVerticalGroup(
            jPanelCrammerRuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrammerRuleLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanelCrammerRuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCrammerRuleLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCrammerRuleLayout.createSequentialGroup()
                        .addComponent(cramersJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Crammer's Rule", jPanelCrammerRule);

        jPanelIntersectingLines.setBackground(new java.awt.Color(102, 153, 255));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coordinates of four points", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("x1:");

        intersectingX1JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectingX1JTextFieldActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("y1");

        intersectingY1JTextField_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectingY1JTextField_IActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("x2:");

        intersectingX2JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectingX2JTextFieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("y2:");

        intersectingY2JTextField_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectingY2JTextField_ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("x3:");

        intersectingX3JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectingX3JTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("y3:");

        intersectingY3JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectingY3JTextFieldActionPerformed(evt);
            }
        });

        intersectingY4JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectingY4JTextFieldActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("y4:");

        intersectingX4JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectingX4JTextFieldActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("x4:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intersectingX4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intersectingY4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intersectingX3JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intersectingY3JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(intersectingX2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(intersectingY2JTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(intersectingX1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(intersectingY1JTextField_I, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(intersectingX1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(intersectingY1JTextField_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(intersectingX2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(intersectingY2JTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(intersectingX3JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(intersectingY3JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(intersectingX4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(intersectingY4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IntersectingJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IntersectingJButton.setText("Calculate");
        IntersectingJButton.setToolTipText("Find the point of intersection of two lines, if there is one.");
        IntersectingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntersectingJButtonActionPerformed(evt);
            }
        });

        intersecting1JTextArea.setEditable(false);
        intersecting1JTextArea.setColumns(20);
        intersecting1JTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        intersecting1JTextArea.setLineWrap(true);
        intersecting1JTextArea.setRows(5);
        intersecting1JTextArea.setText("Enter the four points that generate the two lines: the first two for line 1 and the other two for line 2.");
        intersecting1JTextArea.setWrapStyleWord(true);
        jScrollPane5.setViewportView(intersecting1JTextArea);

        intersecting2JTextArea.setEditable(false);
        intersecting2JTextArea.setColumns(20);
        intersecting2JTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        intersecting2JTextArea.setLineWrap(true);
        intersecting2JTextArea.setRows(5);
        intersecting2JTextArea.setWrapStyleWord(true);
        jScrollPane6.setViewportView(intersecting2JTextArea);

        javax.swing.GroupLayout jPanelIntersectingLinesLayout = new javax.swing.GroupLayout(jPanelIntersectingLines);
        jPanelIntersectingLines.setLayout(jPanelIntersectingLinesLayout);
        jPanelIntersectingLinesLayout.setHorizontalGroup(
            jPanelIntersectingLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIntersectingLinesLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanelIntersectingLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(jPanelIntersectingLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IntersectingJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        jPanelIntersectingLinesLayout.setVerticalGroup(
            jPanelIntersectingLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIntersectingLinesLayout.createSequentialGroup()
                .addGroup(jPanelIntersectingLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelIntersectingLinesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(IntersectingJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelIntersectingLinesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("IntersectingLines", jPanelIntersectingLines);

        jMenuFile.setText("File");

        jMenuItemClear.setText("Clear");
        jMenuItemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClearActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemClear);

        jMenuItem_Print.setText("Print");
        jMenuItem_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PrintActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItem_Print);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuGeometries.setText("Geometries");

        jMenuItem_Quadratic.setText("Quadratic");
        jMenuItem_Quadratic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_QuadraticActionPerformed(evt);
            }
        });
        jMenuGeometries.add(jMenuItem_Quadratic);

        jMenuItemCrammerRule.setText("Crammer's Rule");
        jMenuItemCrammerRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrammerRuleActionPerformed(evt);
            }
        });
        jMenuGeometries.add(jMenuItemCrammerRule);

        jMenuItemIntersectingLines.setText("Intersecting Lines");
        jMenuItemIntersectingLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIntersectingLinesActionPerformed(evt);
            }
        });
        jMenuGeometries.add(jMenuItemIntersectingLines);

        jMenuBar1.add(jMenuGeometries);

        jMenuHelp.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quadraticJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quadraticJButtonActionPerformed
        // TODO add your handling code here:
        calculateQuadratic();
    }//GEN-LAST:event_quadraticJButtonActionPerformed

    private void cramersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cramersJButtonActionPerformed
        // TODO add your handling code here:
        calculateCrammersRule();
    }//GEN-LAST:event_cramersJButtonActionPerformed

    private void IntersectingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntersectingJButtonActionPerformed
        // TODO add your handling code here:
        calculateIntersectingLines();
    }//GEN-LAST:event_IntersectingJButtonActionPerformed

    private void aJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aJTextFieldActionPerformed
        // TODO add your handling code here:
        makeQuadraticJButtonDefault();
    }//GEN-LAST:event_aJTextFieldActionPerformed

    private void bJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJTextFieldActionPerformed
        // TODO add your handling code here:
        makeQuadraticJButtonDefault();
    }//GEN-LAST:event_bJTextFieldActionPerformed

    private void cJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cJTextFieldActionPerformed
        // TODO add your handling code here:
        makeQuadraticJButtonDefault();
    }//GEN-LAST:event_cJTextFieldActionPerformed

    private void crammerA1JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crammerA1JTextFieldActionPerformed
        // TODO add your handling code here:
        makeCrammersJButtonDefault();

    }//GEN-LAST:event_crammerA1JTextFieldActionPerformed

    private void crammerA2JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crammerA2JTextFieldActionPerformed
        // TODO add your handling code here:
        makeCrammersJButtonDefault();
    }//GEN-LAST:event_crammerA2JTextFieldActionPerformed

    private void crammerB1JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crammerB1JTextFieldActionPerformed
        // TODO add your handling code here:
        makeCrammersJButtonDefault();
    }//GEN-LAST:event_crammerB1JTextFieldActionPerformed

    private void crammerB2JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crammerB2JTextFieldActionPerformed
        // TODO add your handling code here:
        makeCrammersJButtonDefault();
    }//GEN-LAST:event_crammerB2JTextFieldActionPerformed

    private void crammerC1JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crammerC1JTextFieldActionPerformed
        // TODO add your handling code here:
        makeCrammersJButtonDefault();
    }//GEN-LAST:event_crammerC1JTextFieldActionPerformed

    private void crammerC2JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crammerC2JTextFieldActionPerformed
        // TODO add your handling code here:
        makeCrammersJButtonDefault();
    }//GEN-LAST:event_crammerC2JTextFieldActionPerformed

    private void intersectingX1JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectingX1JTextFieldActionPerformed
        // TODO add your handling code here:
        makeIntersectingJButtonDefault();
    }//GEN-LAST:event_intersectingX1JTextFieldActionPerformed

    private void intersectingY1JTextField_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectingY1JTextField_IActionPerformed
        // TODO add your handling code here:
        makeIntersectingJButtonDefault();
    }//GEN-LAST:event_intersectingY1JTextField_IActionPerformed

    private void intersectingX2JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectingX2JTextFieldActionPerformed
        // TODO add your handling code here:
        makeIntersectingJButtonDefault();
    }//GEN-LAST:event_intersectingX2JTextFieldActionPerformed

    private void intersectingY2JTextField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectingY2JTextField_ActionPerformed
        // TODO add your handling code here:
        makeIntersectingJButtonDefault();
    }//GEN-LAST:event_intersectingY2JTextField_ActionPerformed

    private void intersectingX3JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectingX3JTextFieldActionPerformed
        // TODO add your handling code here:
        makeIntersectingJButtonDefault();
    }//GEN-LAST:event_intersectingX3JTextFieldActionPerformed

    private void intersectingY3JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectingY3JTextFieldActionPerformed
        // TODO add your handling code here:
        makeIntersectingJButtonDefault();
    }//GEN-LAST:event_intersectingY3JTextFieldActionPerformed

    private void intersectingX4JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectingX4JTextFieldActionPerformed
        // TODO add your handling code here:
        makeIntersectingJButtonDefault();
    }//GEN-LAST:event_intersectingX4JTextFieldActionPerformed

    private void intersectingY4JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectingY4JTextFieldActionPerformed
        // TODO add your handling code here:
        makeIntersectingJButtonDefault();
    }//GEN-LAST:event_intersectingY4JTextFieldActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // TODO add your handling code here:
        AboutJFrame frame = new AboutJFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearActionPerformed
        // TODO add your handling code here:
        crammerA1JTextField.setText("");
        crammerA2JTextField.setText("");
        crammerB1JTextField.setText("");
        crammerB2JTextField.setText("");
        crammerC1JTextField.setText("");
        crammerC2JTextField.setText("");
        intersectingX1JTextField.setText("");
        intersectingX2JTextField.setText("");
        intersectingX2JTextField.setText("");
        intersectingX3JTextField.setText("");
        intersectingX4JTextField.setText("");
        intersectingY1JTextField_I.setText("");
        intersectingY2JTextField_.setText("");
        intersectingY3JTextField.setText("");
        intersectingY4JTextField.setText("");
        aJTextField.setText("");
        bJTextField.setText("");
        cJTextField.setText("");
        crammer2JTextArea.setText("");
        intersecting2JTextArea.setText("");
        quadratic2JTextArea.setText("");
    }//GEN-LAST:event_jMenuItemClearActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Yes", "No"};
        int n = JOptionPane.showOptionDialog(this,
                "Would you realy want to Exit?",
                "",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if (n == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItem_QuadraticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_QuadraticActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItem_QuadraticActionPerformed

    private void jMenuItemCrammerRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrammerRuleActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_jMenuItemCrammerRuleActionPerformed

    private void jMenuItemIntersectingLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIntersectingLinesActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_jMenuItemIntersectingLinesActionPerformed

    private void jMenuItem_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PrintActionPerformed
        // TODO add your handling code here:
        Component cmp = jTabbedPane.getComponentAt(jTabbedPane.getSelectedIndex() /*index of tab*/);
        JPanel pnl = (JPanel)cmp; //cast to JPanel
        printRecord(pnl);
        
        
        
    }//GEN-LAST:event_jMenuItem_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Geometries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Geometries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Geometries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Geometries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Geometries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IntersectingJButton;
    private javax.swing.JTextField aJTextField;
    private javax.swing.JTextField bJTextField;
    private javax.swing.JTextField cJTextField;
    private javax.swing.JButton cramersJButton;
    private javax.swing.JTextArea crammer1JTextArea;
    private javax.swing.JTextArea crammer2JTextArea;
    private javax.swing.JTextField crammerA1JTextField;
    private javax.swing.JTextField crammerA2JTextField;
    private javax.swing.JTextField crammerB1JTextField;
    private javax.swing.JTextField crammerB2JTextField;
    private javax.swing.JTextField crammerC1JTextField;
    private javax.swing.JTextField crammerC2JTextField;
    private javax.swing.JTextArea intersecting1JTextArea;
    private javax.swing.JTextArea intersecting2JTextArea;
    private javax.swing.JTextField intersectingX1JTextField;
    private javax.swing.JTextField intersectingX2JTextField;
    private javax.swing.JTextField intersectingX3JTextField;
    private javax.swing.JTextField intersectingX4JTextField;
    private javax.swing.JTextField intersectingY1JTextField_I;
    private javax.swing.JTextField intersectingY2JTextField_;
    private javax.swing.JTextField intersectingY3JTextField;
    private javax.swing.JTextField intersectingY4JTextField;
    private javax.swing.JComboBox jComboBox_GeometryProblem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuGeometries;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemClear;
    private javax.swing.JMenuItem jMenuItemCrammerRule;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemIntersectingLines;
    private javax.swing.JMenuItem jMenuItem_Print;
    private javax.swing.JMenuItem jMenuItem_Quadratic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCrammerRule;
    private javax.swing.JPanel jPanelIntersectingLines;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelQuadratic;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea quadratic1JTextArea;
    private javax.swing.JTextArea quadratic2JTextArea;
    private javax.swing.JButton quadraticJButton;
    // End of variables declaration//GEN-END:variables

    private void setTitleBar() {
        try {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            Date date = new Date();
            setTitle("Geometries--" + formatter.format(date));
            Image icon = Toolkit.getDefaultToolkit().getImage("resources//icon.png");
            setIconImage(icon);
            setLocationRelativeTo(null);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    private void initializations() {
        jMenuFile.setMnemonic('F');
        jMenuGeometries.setMnemonic('G');
        jMenuHelp.setMnemonic('H');

        jMenuItemClear.setMnemonic('C');
        jMenuItem_Print.setMnemonic('P');
        jMenuItemExit.setMnemonic('E');

        jMenuItem_Quadratic.setMnemonic('Q');
        jMenuItemCrammerRule.setMnemonic('C');
        jMenuItemIntersectingLines.setMnemonic('I');

        jMenuItemAbout.setMnemonic('A');

    }

    private void makeQuadraticJButtonDefault() {
        JRootPane rootPane = SwingUtilities.getRootPane(quadraticJButton);
        rootPane.setDefaultButton(quadraticJButton);
        calculateQuadratic();
    }

    private void makeCrammersJButtonDefault() {
        JRootPane rootPane = SwingUtilities.getRootPane(cramersJButton);
        rootPane.setDefaultButton(cramersJButton);
        calculateCrammersRule();
    }

    private void makeIntersectingJButtonDefault() {
        JRootPane rootPane = SwingUtilities.getRootPane(IntersectingJButton);
        rootPane.setDefaultButton(IntersectingJButton);
        calculateIntersectingLines();
    }

    private void calculateQuadratic() {
        System.out.println("CalculateQuadratic");

        try {

            String value1 = String.valueOf(aJTextField.getText());
            String value2 = String.valueOf(bJTextField.getText());
            String value3 = String.valueOf(cJTextField.getText());

            if (!value1.isEmpty() && !value2.isEmpty() && !value3.isEmpty()) {

                Quadratic qd = new Quadratic(Double.parseDouble(value1), Double.parseDouble(value2), Double.parseDouble(value3));
                quadratic2JTextArea.setText(qd.toString());

            } else {
                JOptionPane.showMessageDialog(null, "Please enter valid values",
                        "Error!!", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Please enter valid values",
                    "Error!!", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void calculateCrammersRule() {
        System.out.println("CalculateCrammersRule");
        try {

            String a1 = String.valueOf(crammerA1JTextField.getText());
            String a2 = String.valueOf(crammerA2JTextField.getText());
            String b1 = String.valueOf(crammerB1JTextField.getText());
            String b2 = String.valueOf(crammerB2JTextField.getText());
            String c1 = String.valueOf(crammerC1JTextField.getText());
            String c2 = String.valueOf(crammerC2JTextField.getText());

            if (!a1.isEmpty() && !a2.isEmpty() && !b1.isEmpty() && !b2.isEmpty() && !c1.isEmpty() && !c2.isEmpty()) {

                CrammersRule crammer = new CrammersRule(Double.parseDouble(a1), Double.parseDouble(a2), Double.parseDouble(b1), Double.parseDouble(b2), Double.parseDouble(c1), Double.parseDouble(c2));
                crammer2JTextArea.setText(crammer.toString());

            } else {
                JOptionPane.showMessageDialog(null, "Please enter valid values",
                        "Error!!", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Please enter valid values",
                    "Error!!", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void calculateIntersectingLines() {
        System.out.println("CalculateIntersectingLines");

        try {
            String x1 = String.valueOf(intersectingX1JTextField.getText());
            String y1 = String.valueOf(intersectingY1JTextField_I.getText());
            String x2 = String.valueOf(intersectingX2JTextField.getText());
            String y2 = String.valueOf(intersectingY2JTextField_.getText());
            String x3 = String.valueOf(intersectingX3JTextField.getText());
            String y3 = String.valueOf(intersectingY3JTextField.getText());
            String x4 = String.valueOf(intersectingX4JTextField.getText());
            String y4 = String.valueOf(intersectingY4JTextField.getText());

            if (!x1.isEmpty() && !y1.isEmpty()
                    && !x2.isEmpty() && !y2.isEmpty()
                    && !x3.isEmpty() && !y3.isEmpty()
                    && !x4.isEmpty() && !y4.isEmpty()) {

                IntersectingLines intersectingLines = new IntersectingLines(Double.parseDouble(x1), Double.parseDouble(y1),
                        Double.parseDouble(x2), Double.parseDouble(y2),
                        Double.parseDouble(x3), Double.parseDouble(y3),
                        Double.parseDouble(x4), Double.parseDouble(y4));
                intersecting2JTextArea.setText(intersectingLines.toString());

            } else {
                JOptionPane.showMessageDialog(null, "Please enter valid values",
                        "Error!!", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Please enter valid values",
                    "Error!!", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void printRecord(JPanel panel){
        // Create PrinterJob Here
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        // Set Printer Job Name
        printerJob.setJobName("Print Record");
        // Set Printable
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                // Check If No Printable Content
                if(pageIndex > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                // Make 2D Graphics to map content
                Graphics2D graphics2D = (Graphics2D)graphics;
                // Set Graphics Translations
                // A Little Correction here Multiplication was not working so I replaced with addition
                graphics2D.translate(pageFormat.getImageableX()+10, pageFormat.getImageableY()+10);
                // This is a page scale. Default should be 0.3 I am using 0.5
                graphics2D.scale(0.5, 0.5);
                
                // Now paint panel as graphics2D
                panel.paint(graphics2D);
                
                // return if page exists
                return Printable.PAGE_EXISTS;
            }
        });
        // Store printerDialog as boolean
        boolean returningResult = printerJob.printDialog();
        // check if dilog is showing
        if(returningResult){
            // Use try catch exeption for failure
            try{
                // Now call print method inside printerJob to print
                printerJob.print();
            }catch (PrinterException printerException){
                JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
            }
        }
    }

}
